Update check_pmg_services

diff --git a/check_pmg_services b/check_pmg_services
--- a/check_pmg_services
+++ b/check_pmg_services
@@ -1,16 +1,17 @@
 #!/bin/bash
 
-###########################################
+################################################################################################
 #
 # Author: Jason Cheng (jason@jason.tools)
 # Date: 2020/07/13
 #
-# Please note that your nrpe target needs 
-# to run "visudo" and add this line:
+# Please note that your nrpe target needs to run "visudo" and add this line:
 # "nagios ALL=NOPASSWD: /bin/systemctl"
 #
-###########################################
-
+# Partial code reference from check_zmcontrol 
+# https://exchange.nagios.org/directory/Plugins/Email-and-Groupware/check_zmcontrol/details
+#
+################################################################################################
 
 STATE_OK=0
 STATE_WARNING=1
@@ -20,11 +21,11 @@ VERSION="v1.0"
 
 usage ()
 {
-    echo "check_pmg_services Nagios plugin by Jason Cheng (jason@jason.tools)"
-    echo "Usage: check_pmg_services [-v]"
-    echo "Options: "
-    echo "-v    Show version"
-    exit $STATE_UNKNOWN
+        echo "check_pmg_services Nagios plugin by Jason Cheng (jason@jason.tools)"
+        echo "Usage: check_pmg_services [-v]"
+        echo "Options: "
+        echo "-v    Show version"
+        exit $STATE_UNKNOWN
 }
 
 if [ $# -eq 0 ]; then
@@ -41,24 +42,24 @@ crit=""
 while [ $# -ne 0 ]
 do
    case "$1" in
-      -v | --version)
-      echo "check_pmg_services $VERSION"
-      exit $STATE_OK
-      ;;
-      -w)
-      shift
-      warn="x"
-      ;;
-      -c)
-      shift
-      crit="x"
-      ;;
-      *)
-      usage
-      exit $STATE_UNKNOWN
-      ;;
-   esac
-   shift
+        -v | --version)
+                echo "check_pmg_services $VERSION"
+                exit $STATE_OK
+                ;;
+        -w)
+                shift
+                warn="x"
+                ;;
+        -c)
+                shift
+                crit="x"
+                ;;
+        *)
+                usage
+                exit $STATE_UNKNOWN
+                ;;
+    esac
+    shift
 done
 
 if [ "$warn" != "" ]
@@ -75,7 +76,6 @@ then
         STATE_PROBLEM=$STATE_CRITICAL
 fi
 
-
 # Get pmg main service status
 sudo /bin/systemctl -a | grep 'clamav-freshclam' > /tmp/pmg_services.txt
 sudo /bin/systemctl -a | grep 'pmg' | grep -v 'sync\|net\|report\|daily\|hourly\|.timer\|.target\|banner' >> /tmp/pmg_services.txt
@@ -90,19 +90,20 @@ number_serv_failed=`cat /tmp/pmg_services.txt | grep -e 'failed\|dead\|exited' |
 if [ "$number_serv_failed" == "0" ]
 then
 
-    getmsg="All services are up and running"
-    #getresult=`cat /tmp/pmg_services.txt | awk '{print "("$4")",$5,$6,$7,$8,$10,$11,$12}' | grep -v 'failed\|dead\|exited'`
-    #getresult2=`echo $getresult | tr "\n\r" " | "`
-    echo $getmsg$getresult2
-    rm -f /tmp/pmg_services.txt
-    exit $STATE_OK
+        getmsg="All services are up and running"
+        #getresult=`cat /tmp/pmg_services.txt | awk '{print "("$4")",$5,$6,$7,$8,$10,$11,$12}' | grep -v 'failed\|dead\|exited'`
+        #getresult2=`echo $getresult | tr "\n\r" " | "`
+        echo $getmsg$getresult2
+        rm -f /tmp/pmg_services.txt
+        exit $STATE_OK
 
 else
 
-    getmsg="Some services have been failed - "
-    getresult=`cat /tmp/pmg_services.txt | awk '{print "("$4")",$5,$6,$7,$8,$10,$11,$12}' | grep -e 'failed\|dead\|exited'`
-    getresult2=`echo $getresult | tr "\n\r" " - "`
-    echo $getmsg$getresult2
-    rm -f /tmp/pmg_services.txt
-    exit $STATE_PROBLEM
+        getmsg="Some services have been failed - "
+        getresult=`cat /tmp/pmg_services.txt | awk '{print "("$4")",$5,$6,$7,$8,$10,$11,$12}' | grep -e 'failed\|dead\|exited'`
+        getresult2=`echo $getresult | tr "\n\r" " - "`
+        echo $getmsg$getresult2
+        rm -f /tmp/pmg_services.txt
+        exit $STATE_PROBLEM
+
 fi
